
version: 2

sources:
  - name: pyingest
    schema: public
    tables:
      - name: lastfm_recent_tracks_json
        description: Raw data ingested via python script.
        columns:
          - name: listen_md5
            tests:
              - not_null
              - unique
      - name: lastfm_loved_tracks_json
        description: Raw data ingested via python script.
        columns:
          - name: love_md5
            tests:
              - not_null
              - unique 

      - name: lastfm_local_files
        description: Raw local files data ingested via python script.
        columns:
          - name: filepath
            tests:
              - not_null
              - unique 

models:
  - name: lastfm_listens_flat
    description: Base model which extracts JSON from the source lastfm table.
    tests:
      - dbt_utils.expression_is_true:
          expression: "_insert_ts_utc > listen_at_ts_utc"
    columns:
      - name: listen_md5
        description: The unique md5 of the listen event, generated by the ingestion script.
        tests:
          - not_null
          - unique
      - name: username
        tests:
          - not_null
      - name: listen_at_ts_utc
        tests:
          - not_null
      - name: track_md5
        description: The md5 of the track name and artist name.
      - name: track_name
        tests:
          - not_null
      - name: track_url
        tests:
          - not_null
      - name: track_mbid
      - name: track_loved_as_of_insert
        description: |
          Boolean for whether the user loved the track at the time of the ingest.
          Join to loves table to determine if the track was loved at play time.
        tests:
          - not_null
          - accepted_values:
              values: [true, false]
      - name: album_md5
        description: The md5 of the album name and artist name.
      - name: album_name
      - name: album_mbid
      - name: artist_md5
        description: The md5 of the artist name.
      - name: artist_name
      - name: artist_url
      - name: artist_mbid
      - name: _insert_ts_utc
        description: The timestamp when the data were ingested.
        tests:
          - not_null

  - name: lastfm_loves_flat
    description: Base model which extracts JSON from the source lastfm table.
    tests:
      - dbt_utils.expression_is_true:
          expression: "_insert_ts_utc > loved_at_ts_utc"
      - unique :
          column_name: "(username || '-' || track_md5)"
    columns:
      - name: love_md5
        description: The unique md5 of the love event, generated by the ingestion script.
        tests:
          - not_null
          - unique
      - name: username
        tests:
          - not_null
      - name: loved_at_ts_utc
        tests:
          - not_null
      - name: loved_at_ts_nyc
        tests:
          - not_null
      - name: track_md5
        description: The md5 of the track name and artist name.
        tests:
          - not_null
      - name: track_name
        tests:
          - not_null
      - name: track_url
        tests:
          - not_null
      - name: track_mbid
      - name: artist_md5
        description: The md5 of the artist name.
      - name: artist_name
      - name: artist_url
      - name: artist_mbid
      - name: _insert_ts_utc
        description: The timestamp when the data were ingested.
        tests:
          - not_null

  - name: lastfm_local_files_flat
    description: |
      Local library file metadata, generated by the ingest script.
      Expect much of these data to be messy, as the tags are very hand entered.
    tests:
      - dbt_utils.expression_is_true:
          expression: "insert_ts_utc > file_created_at"
    columns:
      - name: filepath
        tests:
          - not_null
          - unique
      - name: track_md5
        description: The md5 of the track name and artist name.
      - name: album_md5
        description: The md5 of the album name and artist name.
      - name: artist_md5
        description: The md5 of the artist name.
      - name: file_created_at
        description: |
          Least of file ctime, mtime. This is done due to platform differences in what
          those stamps mean.
        tests:
          - not_null
      - name: track_name
      - name: album_name
      - name: artist_name
      - name: album_artist_name
      - name: derived_artist_name
        description: Album artist or artist.
      - name: track_date
      - name: track_year
        description: First 4 caracters of the date. Skipped if not integers.
      - name: track_length_seconds
      - name: track_mbid
      - name: artist_mbid
      - name: insert_ts_utc
        tests:
          - not_null

  - name: lastfm_tracks
    description: Dimensional model for tracks.
    columns:
      - name: track_md5
        tests:
          - not_null
          - unique
      - name: album_md5
        tests:
          - relationships:
              to: ref('lastfm_albums')
              field: album_md5
      - name: artist_md5
        tests:
          - not_null
          - relationships:
              to: ref('lastfm_artists')
              field: artist_md5
      - name: track_name
        tests:
          - not_null
      - name: track_url
      - name: track_mbid

  - name: lastfm_albums
    description: Dimensional model for albums.
    columns:
      - name: album_md5
        tests:
          - not_null
          - unique
      - name: artist_md5
        tests:
          - not_null
          - relationships:
              to: ref('lastfm_artists')
              field: artist_md5
      - name: album_name
        tests:
          - not_null
      - name: album_mbid

  - name: lastfm_artists
    description: Dimensional model for artists.
    columns:
      - name: artist_md5
        tests:
          - not_null
          - unique
      - name: artist_name
        tests:
          - not_null
      - name: artist_url
      - name: artist_mbid
    
  - name: lastfm_users
    description: Dimensional model for users
    columns:
      - name: username
        tests:
          - not_null
          - unique
      - name: is_dbt_user
        description: Boolean for wherther this user is the target in the dbt_project.yml.
        tests:
          - not_null
      - name: play_count
        tests:
          - not_null
      - name: play_count_7day
        tests:
          - not_null
      - name: play_count_30day
        tests:
          - not_null
      - name: first_play_at_ts_nyc
        tests:
          - not_null
      - name: last_play_at_ts_nyc
        tests:
          - not_null

  - name: artists_30day
    description: Quick view tracking total artist plays in the last 30 days.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - artist_md5
            - username

  - name: artists_monthly_top5
    description: Pivoted top artists from each month for each user.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - month_start
            - username

  - name: tracks_7day
    description: Quick view tracking total track plays in the last 7 days.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - track_md5
            - username

  - name: loved_tracks
    description: Aggregates on each user's loved tracks.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - track_md5
            - username

  - name: albums_alltime
    description: Aggregates on album listening.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - username
            - album_md5

  - name: track_play_spikes
    desciption: Records of play spikes (cases where one track was played >=5 times in 24h).
    columns:
      - name: start_listen_md5
        tests:
          - not_null
          - unique

  - name: local_albums_with_no_listens
    desciption: List of local album names that have no listens in lastfm (by the target user).
    columns:
      - name: album_md5
        tests:
          - not_null
          - unique
