
version: 2

sources:
  - name: pyingest
    schema: public
    tables:
      - name: listenbrainz_listens
        description: Raw data ingested via python script.
        columns:
          - name: listen_md5
            tests:
              - not_null
              - unique

      - name: listenbrainz_user_feedback
        description: Feedback data ingested via python script.
        columns:
          - name: feedback_md5
            tests:
              - not_null
              - unique

      - name: local_music_embeddings
        description: Embeddings from the ml service.
        columns:
          - name: filepath
            tests:
              - not_null
              - unique 

      - name: local_music_files
        description: Raw local files data ingested via python script.
        columns:
          - name: filepath
            tests:
              - not_null
              - unique 

      - name: messybrainz_name_map
        description: Mapped local file data to musicbrainz data.
        columns:
          - name: recording_md5
            tests:
              - not_null
              - unique 

      - name: musicbrainz_annotations
        description: Annotated data from musicbrainz. Long format, uniqe on mbid.
        columns:
          - name: mbid
            tests:
              - not_null
              - unique 
          - name: entity
            tests:
              - not_null
          - name: ts_utc
            tests:
              - not_null
          - name: payload_json

      - name: listenbrainz_similar_user_activity
        description: Activity from users marked as similar on Listenbrainz.
        columns:
          - name: payload_id
            tests:
              - not_null
              - unique 
          - name: from_username
            tests:
              - not_null
          - name: to_username
            tests:
              - not_null
          - name: entity
            tests:
              - not_null
          - name: time_range
            tests:
              - not_null
          - name: user_similarity
            tests:
              - not_null
          - name: json_data
            tests:
              - not_null
          - name: insert_ts_utc
            tests:
              - not_null

      - name: listenbrainz_artist_stats
        description: Artist stats from listenbrainz.
        columns:
          - name: mbid
            tests:
              - not_null
              - unique 
          - name: payload_json
            tests:
              - not_null
          - name: ts_utc
            tests:
              - not_null