
version: 2

sources:
  - name: pyingest
    schema: public
    tables:
      - name: listenbrainz_listens
        description: Raw data ingested via python script.
        columns:
          - name: listen_md5
            tests:
              - not_null
              - unique

      - name: local_music_files
        description: Raw local files data ingested via python script.
        columns:
          - name: filepath
            tests:
              - not_null
              - unique 

      - name: musicbrainz_annotations
        description: Annotated data from musicbrainz. Long format, uniqe on mbid.
        columns:
          - name: mbid
            tests:
              - not_null
              - unique 
          - name: entity
            tests:
              - not_null
          - name: ts_utc
            tests:
              - not_null
          - name: payload_json