version: '3'
services:
  http:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - MOOMOO_POSTGRES_URI=${MOOMOO_DOCKER_POSTGRES_URI:-default}
      - MOOMOO_DBT_SCHEMA=${MOOMOO_DBT_SCHEMA:-default}
      - MOOMOO_INGEST_SCHEMA=${MOOMOO_INGEST_SCHEMA}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5000:8080" ## TODO: expose this somehow?

  moomoo:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - MOOMOO_POSTGRES_URI=${MOOMOO_DOCKER_POSTGRES_URI:-default}
      - MOOMOO_DBT_PG_HOST=${MOOMOO_DBT_PG_HOST:-default}
      - MOOMOO_DBT_PG_PORT=${MOOMOO_DBT_PG_PORT:-default}
      - MOOMOO_DBT_PG_USER=${MOOMOO_DBT_PG_USER:-default}
      - MOOMOO_DBT_PG_DBNAME=${MOOMOO_DBT_PG_DBNAME:-default}
      - MOOMOO_DBT_PG_SCHEMA=${MOOMOO_DBT_PG_SCHEMA:-default}
      - MOOMOO_DBT_PG_PASSWORD=${MOOMOO_DBT_PG_PASSWORD:-default}
      - MOOMOO_CONTACT_EMAIL=${MOOMOO_CONTACT_EMAIL:-default}
      - MOOMOO_DBT_SCHEMA=${MOOMOO_DBT_SCHEMA:-default}
      - MOOMOO_INGEST_SCHEMA=${MOOMOO_INGEST_SCHEMA:-default}

    volumes:
    - ${MOOMOO_MOUNT_LOCAL_MUSIC_DIR:-default}:/mnt/moomoo/music

    extra_hosts:
      - "host.docker.internal:host-gateway"

    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
