
version: 2


models:
  - name: track_play_spikes
    description: Records of play spikes (cases where one track was played >=5 times in 24h).
    columns:
      - name: start_listen_md5
        tests:
          - not_null
          - unique

  - name: listens_by_year
    description: Listening statistics by recording year.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - username
            - release_year

  - name: similar_user_recommends
    description: Top mbids listened to by similar users but not by the user themselves.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - username
            - time_range
            - entity
            - mbid

  - name: fresh_releases
    description: Albums from artists without a lot of listens, ranked by similar user score.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - username
            - rank

  - name: top_releases_by_release_year
    description: Top 5 most listened to releases for each release year.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - username
            - release_year
            - rank
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - username
            - release_mbid
