
version: 2


models:
  - name: map__file_artist
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - filepath
            - artist_mbid
    columns:
      - name: filepath
        tests:
          - not_null
      - name: artist_mbid
        tests:
          - not_null

  - name: map__file_recording
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - recording_mbid
            - filepath
      - groupby_having:
          group: filepath
          having_condition: count(1) <= 2
    columns:
      - name: recording_mbid
        tests:
          - not_null
      - name: filepath
        tests:
          - not_null

  - name: map__file_release
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - release_mbid
            - filepath
      - groupby_having:
          group: filepath
          having_condition: count(1) <= 2
    columns:
      - name: release_mbid
        tests:
          - not_null
      - name: filepath
        tests:
          - not_null

  - name: map__file_release_group
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - release_group_mbid
            - filepath
      - groupby_having:
          group: filepath
          having_condition: count(1) <= 2
    columns:
      - name: release_group_mbid
        tests:
          - not_null
      - name: filepath
        tests:
          - not_null

  - name: map__recording_release
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - recording_mbid
            - release_mbid
    columns:
      - name: recording_mbid
        tests:
          - not_null
      - name: release_mbid
        tests:
          - not_null

  - name: map__release_group_artist
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - release_group_mbid
            - artist_mbid
    columns:
      - name: release_group_mbid
        tests:
          - not_null
      - name: artist_mbid
        tests:
          - not_null

