name: client

on:
  push:
    paths:
      - client/**
      - .github/workflows/client.yml

defaults:
  run:
    working-directory: ./client

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyv: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyv }}

      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-client-${{matrix.pyv}}-${{ hashFiles('client/setup.py') }}

      - name: pip install
        run: |
          pip install pip==23.*
          pip install .[test]

      - name: lint
        run: make lint
      
      - name: test
        run: make test

  # run only on main branch
  store-production-version:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Print the current version
        run: cat src/moomoo_client/version

      - name: Upload to github artifacts
        uses: actions/upload-artifact@v3
        with:
          name: version
          path: client/src/moomoo_client/version

  # run not on main, in pull request
  check-version-changed:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download the production version artifact
        continue-on-error: true # if the artifact does not exist
        id: download-version
        uses: actions/download-artifact@v3
        with:
          name: version
          path: client/version.txt

      - name: Compare versions
        # runs in client/, so can reference version.txt instead of client/version.txt
        run: |
          # check if the artifact exists, if not exit 0.
          if [ ! -f version.txt ]; then
            echo "Production version not found"
            exit 0
          fi

          pr_version=$(cat src/moomoo_client/version)

          echo "Production version: $(cat version.txt)"
          echo "Pull request version: $pr_version"
          if [ "$(cat version.txt)" == "$pr_version" ]; then
            echo "Version has not changed"
            exit 1
          else
            echo "Version has changed"
          fi
