name: client

on:
  push:
    paths:
      - client/**
      - .github/workflows/client.yml

defaults:
  run:
    working-directory: ./client

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyv: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyv }}

      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-client-${{matrix.pyv}}-${{ hashFiles('client/setup.py') }}

      - name: pip install
        run: |
          pip install pip==23.*
          pip install .[test]

      - name: lint
        run: make lint
      
      - name: test
        run: make test

  check-version-changed:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check version changed.
        uses: brettcannon/check-for-changed-files@v1
        with:
          file-pattern: "client/src/moomoo_client/version"
          skip-label: "skip-version"
          failure-message: "Missing a version change in ${file-pattern}. Add one or apply ${skip-label}."