name: client

on:
  push:
    paths:
      - client/**
      - .github/workflows/client.yml

defaults:
  run:
    working-directory: ./client

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyv: ['3.9', '3.10', '3.11', '3.12']

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{matrix.pyv}}-lint-test
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyv }}

      - name: toga deps
        run: | 
          sudo apt update -y
          sudo apt install 
            pkg-config \
            python3-dev \
            libgirepository1.0-dev \
            libcairo2-dev \
            gir1.2-webkit2-4.0 \
            libcanberra-gtk3-module

      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-client-${{matrix.pyv}}-${{ hashFiles('client/setup.py') }}

      - name: pip install
        run: |
          pip install pip==23.*
          pip install .[test]

      - name: lint
        run: make lint

      - name: test
        run: make test

  check-version-changed:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wait 10s
        run: sleep 10  # in case the pr is very new
      - name: Get changed files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          changed=$(gh pr diff --name-only)
          echo Changed files:
          echo $changed
          if [[ $changed != *"client/src/moomoo_client/version"* ]]; then
            echo "No changes to version file"
            exit 1
          fi

