name: dbt

on:
  push:
    paths:
      - dbt/**
      - .github/workflows/dbt.yml

defaults:
  run:
    working-directory: ./dbt

jobs:
  lint-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DBT_HOST: localhost
      DBT_PORT: 5432
      DBT_USER: postgres
      DBT_PASSWORD: postgres
      DBT_DBNAME: postgres
      DBT_SCHEMA: public
      DBT_SSLMODE: disable

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-lint-test
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            dbt/requirements.txt
            dbt/requirements-dev.txt

      - name: dbt deps cache
        uses: actions/cache@v4
        id: dbt_deps_cache
        with:
          path: dbt/dbt_packages
          key: dbt-${{ hashFiles('dbt/packages.yml') }}

      - name: pip install
        run: pip install -r requirements-dev.txt

      - name: dbt deps
        run: dbt deps
        if: ${{ steps.dbt_deps_cache.outputs.cache-hit != 'true' }}

      - name: dbt compile
        run: |
          cp docker-profiles.yml profiles.yml
          dbt compile

      - name: sqlfluff lint
        run: make lint


  check-version-changed:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    # TODO: make this check the actual version number changed, not just the file
    steps:
      - uses: actions/checkout@v4
      - name: wait 10s  # in case the pr is very new
        run: sleep 10
      - name: Get changed files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          changed=$(gh pr diff --name-only)
          echo Changed files:
          echo $changed
          if [[ $changed != *"dbt/dbt_project.yml"* ]]; then
            echo "No changes to dbt_project file"
            exit 1
          fi
