name: http

on:
  push:
    paths:
      - http/**
      - .github/workflows/http.yml

defaults:
  run:
    working-directory: ./http

jobs:
  lint-test:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-lint-test
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - uses: ankane/setup-postgres@v1
        with:
          postgres-version: 14

      - name: install pgvector
        run: |
          sudo apt install curl ca-certificates gnupg

          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc \
            | gpg --dearmor \
            | sudo tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg \
            >/dev/null

          sudo sh -c \
            'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" \
            > /etc/apt/sources.list.d/pgdg.list'

          sudo apt update
          sudo apt install postgresql-server-dev-14
          sudo apt install postgresql-14-pgvector

      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-http-${{ hashFiles('http/setup.py') }}

      - name: pip install
        run: |
          pip install pip==23.*
          pip install .[test]

      - name: lint
        run: make lint

      - name: test
        run: make test

  check-version-changed:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          changed=$(gh pr diff --name-only)
          echo Changed files:
          echo $changed
          if [[ $changed != *"http/src/moomoo_http/version"* ]]; then
            echo "No changes to version file"
            exit 1
          fi

