name: ml

on:
  push:
    paths:
      - ml/**
      - .github/workflows/ml.yml

defaults:
  run:
    working-directory: ./ml

jobs:
  lint-test:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-lint-test
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: ml/setup.py

      - name: Install pgvector
        run: |
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
          sudo apt-get install postgresql-14-pgvector

      - name: ml cache
        uses: actions/cache@v4
        id: ml_cache
        with:
          path: ml/artifacts
          key: moomoo-${{ hashFiles('ml/src/moomoo_ml/scorer/model-info.json') }}

      - name: pip install
        run: |
          pip install pip==23.*
          pip install .[test]

      - name: Download ML Artifacts
        if: steps.ml_cache.outputs.cache-hit != 'true'
        run: moomoo-ml save-artifacts

      - name: lint
        run: make lint

      - name: test
        run: make test

  check-version-changed:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wait 10s
        run: sleep 10  # in case the pr is very new
      - name: Get changed files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          changed=$(gh pr diff --name-only)
          echo Changed files:
          echo $changed
          if [[ $changed != *"ml/src/moomoo_ml/version"* ]]; then
            echo "No changes to version file"
            exit 1
          fi

