name: Unit Tests

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3

      - uses: ankane/setup-postgres@v1
        with:
          postgres-version: 14
      - name: install pgvector
        run: |
          sudo apt install curl ca-certificates gnupg

          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc \
            | gpg --dearmor \
            | sudo tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg \
            >/dev/null

          sudo sh -c \
            'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" \
            > /etc/apt/sources.list.d/pgdg.list'
          
          sudo apt update
          sudo apt install postgresql-server-dev-14
          sudo apt install postgresql-14-pgvector

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-py${{ matrix.python-version }}-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-py${{ matrix.python-version }}-

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[test]

      - name: Black
        run: make py-lint

      - name: Python Unit Tests
        run: make py-test
        env:
          CONTACT_EMAIL: fake